name: finance_manager
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cloud_firestore: ^4.13.1
  firebase_core: ^2.22.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_slidable: ^3.0.1
  pie_chart: ^5.4.0
  firebase_auth: ^4.14.0
  flutter_secure_storage: ^9.0.0
  flutter_colorpicker: ^1.0.3
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  fl_chart: ^0.64.0
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  forex_conversion: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/user_image.jpg
  fonts:
    - family: MyIconsClass
      fonts:
        - asset: assets/fonts/MyIconsClass.ttf
